Repository GSA/code-gov-web, pull requests merged in 2018-07, with the labels that each got.

#599 Roadmap updates
  config/examples/code-dot-gov.json
  package-lock.json
Labels: [Type] Enhancement

#609 Fix Help Wanted UI bug in buttons
  src/app/components/help-wanted/card/help-wanted-card.template.html
Labels: [Problems] bug non-critical, [Type] Bug

#604 adding labor hours md to root files on GH and linking from compliance guidan…
  src/app/components/policy-guide/docs/compliance/compliance-inventory-code/compliance-inventory-code.template.html
Labels: [Improvements] enhancement
